// Supported grammars for different langauges

// Default config for golden-layout windows
export const defaultGLConfig: any = {
  root: {
    type: "row",
    content: [
      {
        type: "column",
        content: [
          {
            type: "stack",
            content: [
              {
                type: "component",
                content: [],
                width: 50,
                minWidth: 0,
                height: 50,
                minHeight: 0,
                id: "",
                maximised: false,
                isClosable: true,
                reorderEnabled: true,
                title: "Input",
                componentType: "inputArea",
                componentState: {},
              },
            ],
            width: 50,
            minWidth: 0,
            height: 25,
            minHeight: 0,
            id: "",
            isClosable: true,
            maximised: false,
            activeItemIndex: 0,
          },
          {
            type: "stack",
            content: [
              {
                type: "component",
                content: [],
                width: 50,
                minWidth: 0,
                height: 50,
                minHeight: 0,
                id: "",
                maximised: false,
                isClosable: true,
                reorderEnabled: true,
                title: "Console",
                componentType: "consoleArea",
                componentState: {},
              },
            ],
            width: 50,
            minWidth: 0,
            height: 25,
            minHeight: 0,
            id: "",
            isClosable: true,
            maximised: false,
            activeItemIndex: 0,
          },
        ],
        width: 38.606004410776265,
        minWidth: 0,
        height: 50,
        minHeight: 0,
        id: "",
        isClosable: true,
      },
      {
        type: "stack",
        content: [
          {
            type: "component",
            content: [],
            width: 50,
            minWidth: 0,
            height: 50,
            minHeight: 0,
            id: "",
            maximised: false,
            isClosable: true,
            reorderEnabled: true,
            title: "Output",
            componentType: "outputArea",
            componentState: {},
          },
        ],
        width: 34.96539155329698,
        minWidth: 0,
        height: 50,
        minHeight: 0,
        id: "",
        isClosable: true,
        maximised: false,
        activeItemIndex: 0,
      },
    ],
    width: 50,
    minWidth: 0,
    height: 50,
    minHeight: 0,
    id: "",
    isClosable: true,
  },
  openPopouts: [],
  settings: {
    constrainDragToContainer: true,
    reorderEnabled: true,
    popoutWholeStack: false,
    blockedPopoutsThrowError: true,
    closePopoutsOnUnload: true,
    responsiveMode: "none",
    tabOverlapAllowance: 0,
    reorderOnTabMenuClick: true,
    tabControlOffset: 10,
    popInOnClose: false,
  },
  dimensions: {
    borderWidth: 5,
    borderGrabWidth: 5,
    minItemHeight: 10,
    minItemWidth: 10,
    headerHeight: 20,
    dragProxyWidth: 300,
    dragProxyHeight: 200,
  },
  header: {
    show: "top",
    popout: "open in new window",
    dock: "dock",
    close: "close",
    maximise: "maximise",
    minimise: "minimise",
    tabDropdown: "additional tabs",
  },
  resolved: true,
};
